development:
  adapter: postgresql
  encoding: unicode
  database: terse_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: terse_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: terse_production
  pool: 5
